# Generated by Django 6.0 on 2025-12-23 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('message', models.TextField(max_length=1000)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_read', 'created_at'], name='bookings_co_is_read_cd96b6_idx')],
            },
        ),
        migrations.CreateModel(
            name='GymClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('class_type', models.CharField(choices=[('PERSONAL', 'Personal Training'), ('GROUP', 'Group Fitness'), ('YOGA', 'Yoga'), ('STRENGTH', 'Strength'), ('CARDIO', 'Cardio'), ('NUTRITION', 'Nutrition')], max_length=20)),
                ('description', models.TextField()),
                ('duration_minutes', models.IntegerField(default=60)),
                ('max_participants', models.IntegerField(default=20)),
                ('instructor', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active', 'class_type'], name='bookings_gy_is_acti_74519a_idx')],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('available_spots', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('gym_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='bookings.gymclass')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_reference', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='CONFIRMED', max_length=20)),
                ('special_requests', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gym_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='bookings.gymclass')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='bookings.timeslot')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['is_available', 'start_time'], name='bookings_ti_is_avai_4e0a80_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('gym_class', 'start_time')},
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['email', 'status', 'created_at'], name='bookings_bo_email_90a5d5_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'CONFIRMED'])), fields=('email', 'time_slot'), name='unique_active_booking'),
        ),
    ]
